### ISSUE TITLE
TypeError: add_node() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by aponom84** [rabbanyk/FARZ#1]
When I'm trying to run FARZ with arguments from example, I get error "TypeError: add_node() takes exactly 2 arguments (3 given)"
-----
```
python FARZ.py -n 1000 -m 5 -k 4 --beta 0.9

Traceback (most recent call last):
  File "FARZ.py", line 657, in <module>
    FARZ(sys.argv[1:])
  File "FARZ.py", line 653, in FARZ
    G,C = generate( **batch_setting)
  File "FARZ.py", line 477, in generate
    write_to_file(G,C,path,name,format,farz_params)
  File "FARZ.py", line 447, in write_to_file
    Gnx = G.to_nx(C)   
  File "FARZ.py", line 104, in to_nx
    G.add_node(i, {'c':str(C.memberships[i])})
TypeError: add_node() takes exactly 2 arguments (3 given)
```

**Comment by aponom84** [comment]
The problem was that FARZ uses networkx library version 1.10, but version is 2.3 that is installed by default. To void this, use ```pip install networkx==1.11```
